# Generated by Django 5.2.7 on 2025-11-09 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('core_productos', '0003_producto_creado_por_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff que realizó la compra'),
        ),
    ]
