# Generated by Django 5.2.7 on 2025-11-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa de Bebé'), ('juguetes', 'Juguetes y Didácticos'), ('accesorios', 'Accesorios'), ('cuidado', 'Cuidado Personal'), ('calzado', 'zapatos y zapatillas')], default='accesorios', max_length=20, verbose_name='Categoría'),
        ),
    ]
