# Generated by Django 5.2.7 on 2025-11-09 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0003_producto_creado_por_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa de Bebé'), ('juguetes', 'Juguetes y Didácticos'), ('accesorios', 'Accesorios'), ('cuidado', 'Cuidado Personal'), ('Zapatos y Zapatillas', 'calzado')], default='accesorios', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
