# Generated by Django 5.2.7 on 2025-11-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0004_alter_producto_categoria_alter_producto_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa de Bebé'), ('juguetes', 'Juguetes y Didácticos'), ('accesorios', 'Accesorios'), ('cuidado', 'Cuidado Personal'), ('calzado', 'Zapatos y Zapatillas')], default='accesorios', max_length=20, verbose_name='Categoría'),
        ),
    ]
