# Generated by Django 5.2.7 on 2025-11-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0005_producto_imagen_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ganancia %'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa de Bebé'), ('juguetes', 'Juguetes y Didácticos'), ('accesorios', 'Accesorios'), ('cuidado', 'Cuidado Personal'), ('Zapatos y Zapatillas', 'calzado')], default='accesorios', max_length=20, verbose_name='Categoría'),
        ),
    ]
