# Generated by Django 5.2.7 on 2025-11-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0006_remove_producto_imagen_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
