# Generated by Django 5.2.7 on 2026-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_productos', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
    ]
