# Generated by Django 5.2.7 on 2025-11-09 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_productos', '0002_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_productos.producto')),
            ],
            options={
                'verbose_name': 'Compra de Inventario',
                'verbose_name_plural': 'Compras de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('R', 'Entregado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_productos.producto')),
                ('usuario', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final de la venta.', max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pedidos.pedido')),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol__in': ['administrador', 'vendedor']}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_gestionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta (Transacción Cerrada)',
                'verbose_name_plural': 'Ventas (Transacciones Cerradas)',
            },
        ),
    ]
