# Generated by Django 5.2.7 on 2025-12-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pago_monto_pagado_remove_pago_pedido_and_more'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asociados', to='pagos.transaccioncompra', verbose_name='Transacción de Compra'),
        ),
    ]
