# Generated by Django 5.2.7 on 2025-12-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='transaccion',
        ),
    ]
