# Generated by Django 5.2.7 on 2025-12-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_initial'),
        ('pedidos', '0003_remove_pedido_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pagos.pago', verbose_name='Pago'),
        ),
    ]
