# Generated by Django 5.2.7 on 2025-12-16 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.CreateModel(
            name='TransaccionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Transacción')),
                ('total_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total de la Compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Transacción de Compra',
                'verbose_name_plural': 'Transacciones de Compra',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pago_asociado', to='pagos.transaccioncompra', verbose_name='Transacción Asociada'),
            preserve_default=False,
        ),
    ]
