# Generated by Django 5.2.7 on 2025-12-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pago_monto_pagado_remove_pago_pedido_and_more'),
        ('pedidos', '0003_remove_pedido_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncompra',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='TransaccionCompra',
        ),
    ]
