# Generated by Django 5.2.7 on 2026-01-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='foto_verificacion',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones/', verbose_name='Foto de Verificación'),
        ),
    ]
