# Generated by Django 5.2.7 on 2026-01-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pago_foto_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='codigo_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='foto_verificacion',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones/', verbose_name='Foto del comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia bancaria')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
