# Generated by Django 5.2.7 on 2026-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_pago_codigo_comprobante_alter_pago_foto_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='codigo_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de comprobante bancario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='foto_verificacion',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion_comprobante/', verbose_name='Imagen de verificación / comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
